# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: {{ kube_cert_dir }}/ca.pem
    server: http://127.0.0.1:8080
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
