# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
  {{ kube_api_audit_rules_list | to_nice_yaml(indent=2) | indent(width=2, indentfirst=False) }}
